version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: wallet_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d # Mount migrations directory
    networks:
      - wallet_network

  redis:
    image: redis:latest
    container_name: wallet_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - wallet_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_cli_app
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - wallet_network

volumes:
  postgres_data:

networks:
  wallet_network:
    driver: bridge